# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.warning.mode=fail

# Fabric Properties
# Check these at https://fabricmc.net/develop/ and
# https://modrinth.com/mod/fabric-api/versions
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.155.2+26.1.2

# Mod Properties
mod_version=v7.55.1-MC26.1.2
maven_group=net.wurstclient
archives_base_name=Wurst-Client
mod_loader=Fabric

# GitHub
gh_repo_id=Wurst-Imperium/Wurst7
mcx_repo_id=Wurst-Imperium/Wurst-MCX2

# Mod versions for automated compatibility tests:
# Check at https://modrinth.com/mod/sodium/versions?l=fabric&g=26.1.2
sodium_version=mc26.1.2-0.9.2-alpha.4-fabric
# Check at https://modrinth.com/mod/lootr/versions?l=fabric&g=26.1.2
lootr_version=m1PLActz

# For manual testing (uncomment as needed):
# Check at https://modrinth.com/mod/better-block-entities/versions?g=26.1.2
#better_block_entities_version=1.3.7-beta.1+mc26.1.2
# Check at https://modrinth.com/mod/badoptimizations/versions?g=26.1.2
#badoptimizations_version=gjIvugXc
# Check at https://modrinth.com/mod/shoulder-surfing-reloaded/versions?l=fabric&g=26.1.2
#shoulder_surfing_version=26.1.2-5.0.11+fabric
# Shoulder Surfing requires Forge Config API Port:
# Check at https://modrinth.com/mod/forge-config-api-port/versions?l=fabric&g=26.1.2
#forge_config_api_port_version=jUe0ucoE
