name: Bug Report
description: Report a bug
labels: ["type:bug", "status:unconfirmed"]
body:
- type: markdown
  attributes:
    value: |
      ## Welcome!
      Please fill out the following template to help us understand and reproduce the issue you're experiencing.
- type: checkboxes
  id: checklist
  attributes:
    label: Pre-reporting checklist
    description: "Please select all that apply."
    options:
      - label: "I have searched existing issues and didn't find any previous reports of this bug."
      - label: "This bug still happens in the latest version of Wurst. I've made sure my installation is up to date."
      - label: "I have tried removing all other mods and the bug still happens."
- type: textarea
  id: description
  attributes:
    label: Description
    description: "Please describe the bug in as much detail as possible."
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Repro steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    placeholder: |
      1.
      2.
      3.
  validations:
    required: true
- type: input
  id: wurst-version
  attributes:
    label: Wurst Client version
    placeholder: e.g. 7.15
  validations:
    required: true
- type: input
  id: minecraft-version
  attributes:
    label: Minecraft version
    placeholder: e.g. 1.16.5
  validations:
    required: true
- type: textarea
  id: crash
  attributes:
    label: Crash report (if applicable)
    description: "If your game crashed, please paste the entire crash report here."
    placeholder: |
      ---- Minecraft Crash Report ----
      // Who set us up the TNT?
    render: plaintext
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      ## Thank you!
      We appreciate your help in improving Wurst Client by reporting this bug. Please make sure you have filled out all the necessary information before submitting this issue.
