name: "Close stale issues / pull requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: |
            This issue has been open for a while. It will be closed soon if nobody comments on it.  
            Issues should be closed if:
              - They are duplicates of other issues
              - There is not enough demand
              - They are no longer relevant
              - There are not enough details
          days-before-stale: 60
          days-before-close: 30
